# Generated by Django 5.2.5 on 2025-08-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='qyantity',
            new_name='quantity',
        ),
    ]
