# Generated by Django 5.2.5 on 2025-08-16 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderitems', '0001_initial'),
        ('products', '0003_alter_products_price_alter_products_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='user',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='product',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='products.products'),
            preserve_default=False,
        ),
    ]
