# Generated by Django 5.2.5 on 2025-08-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
