# Generated by Django 5.2.5 on 2025-08-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customeuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='customeuser',
            name='status',
        ),
    ]
