# Generated by Django 5.2.5 on 2025-08-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_customeuser_role_remove_customeuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], default='user', max_length=50),
        ),
        migrations.AddField(
            model_name='customeuser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'InActive')], default='active', max_length=50),
        ),
    ]
