# Generated by Django 5.2.5 on 2025-08-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customeuser_role_customeuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], default='customer', max_length=50),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50),
        ),
    ]
