# Generated by Django 5.2.5 on 2025-08-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
