# Generated by Django 5.2.5 on 2025-08-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupons',
            old_name='discount',
            new_name='discount_value',
        ),
    ]
