# Generated by Django 5.2.5 on 2025-08-19 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_rename_discount_coupons_discount_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='coupons',
            name='valid_to',
        ),
    ]
